# Meta Data for SEO

## Homepage
title = "Staq.js"
titleSeparator = "-"
titleAddition = "A JavaScript Library for building SaaS products"
description = "Staq.js is a React library that comes with tools for building software people pay you for"

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "staqjs"
twitterCreator = "mattroll_"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "staq-logo.png"
schemaTwitter = "https://twitter.com/mattroll_"
schemaGitHub = "https://github.com/staqjs"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://github.com/\">GitHub</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/staqjs/staqjs.com/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/staqjs/staqjs.com"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
